name: Continous Integration

on:
  pull_request:
    branches: 
      - main
      
jobs:
  automation-test-job:
    name: vitest test
    runs-on: ubuntu-latest
    
    steps:
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
      - name: Install dependencies
        run: pnpm install
      - name: Test with Vitest
        run: pnpm test
